server:
  servlet:
    context-path: /api
  port: 9092
  
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://lemur-4.cloud-iam.com/auth/realms/kingmenu-auth-server
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
          
jwt:
  auth:
    converter:
      resourceId: kingmenu-client
      principalAttribute: preferred_username
      
