server:
  port: 8080

spring:
  application:
    name: entity-management
  data:
    mongodb:
      uri: mongodb://luizcardoso:rca1995@cluster0-shard-00-00.e7mjo.mongodb.net:27017,cluster0-shard-00-01.e7mjo.mongodb.net:27017,cluster0-shard-00-02.e7mjo.mongodb.net:27017/test?replicaSet=atlas-pdlssx-shard-0&ssl=true&authSource=admin
      database: entity

authserver:
  hostname: http://localhost:9090
  security:
    oauth2:
      resource:
        id: ${spring.application.name}
        userInfoUri: ${authserver.hostname}/api/auth/token

jwt:
  auth:
    converter:
      resource-id: kingmenu-client
      principal-attribute: preferred_username
