server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: entity-management
   data:
    mongodb:
      uri: mongodb://luizcardoso:rca1995@cluster0-shard-00-00.e7mjo.mongodb.net:27017,cluster0-shard-00-01.e7mjo.mongodb.net:27017,cluster0-shard-00-02.e7mjo.mongodb.net:27017/test?replicaSet=atlas-pdlssx-shard-0&ssl=true&authSource=admin
      database: entity
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://lemur-4.cloud-iam.com/auth/realms/kingmenu-auth-server
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
          
jwt:
  auth:
    converter:
      resource-id: kingmenu-client
      principal-attribute: preferred_username
      
eureka:
  instance:
    hostname: localhost
    port: 9999
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

logging:
  level:
    org.springframework.security: DEBUG
    
